#!/bin/sh
initialize() {
  jack_control ds alsa
  lsusb | grep Focusrite-Novation &&
    (echo "Scarlett"; jack_control dps device hw:2) ||
    (echo "No Scarlett"; jack_control dps device hw:PCH)
  pasuspender jack_control start
  pactl load-module module-jack-sink client_name=Pulse_Sink
  pactl load-module module-jack-source client_name=Pulse_Source
}

jack_control stop
jack_control status | grep stopped &&
  initialize ||
  notify-send -u critical "Failed to start JACK server"
