# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "uas" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

  fileSystems."/sconapool" =
    { device = "sconapool";
      fsType = "zfs";
    };

  fileSystems."/sconapool/guava" =
    { device = "sconapool/guava";
      fsType = "zfs";
    };

  fileSystems."/sconapool/guava/anime" =
    { device = "sconapool/guava/anime";
      fsType = "zfs";
    };

  fileSystems."/sconapool/kathryn-drive" =
    { device = "sconapool/kathryn-drive";
      fsType = "zfs";
    };

  fileSystems."/sconapool/getcooking" =
    { device = "sconapool/getcooking";
      fsType = "zfs";
    };

  fileSystems."/sconapool/guava/music" =
    { device = "sconapool/guava/music";
      fsType = "zfs";
    };

  fileSystems."/sconapool/getcooking/branding" =
    { device = "sconapool/getcooking/branding";
      fsType = "zfs";
    };

  fileSystems."/sconapool/getcooking/video" =
    { device = "sconapool/getcooking/video";
      fsType = "zfs";
    };

  fileSystems."/sconapool/getcooking/video/project-archive" =
    { device = "sconapool/getcooking/video/project-archive";
      fsType = "zfs";
    };

  fileSystems."/sconapool/getcooking/video/raw-footage" =
    { device = "sconapool/getcooking/video/raw-footage";
      fsType = "zfs";
    };

  fileSystems."/flashpool" =
    { device = "flashpool";
      fsType = "zfs";
    };

  fileSystems."/flashpool/music" =
    { device = "flashpool/music";
      fsType = "zfs";
    };

  fileSystems."/flashpool/anime" =
    { device = "flashpool/anime";
      fsType = "zfs";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
